// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.services.blocking.model

import ai.hanzo.api.TestServerExtension
import ai.hanzo.api.client.okhttp.HanzoOkHttpClient
import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.models.model.ModelInfo
import ai.hanzo.api.models.model.update.UpdateDeployment
import ai.hanzo.api.models.model.update.UpdatePartialParams
import java.time.OffsetDateTime
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class UpdateServiceTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun full() {
        val client =
            HanzoOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .apiKey("My API Key")
                .build()
        val updateService = client.model().update()

        val response =
            updateService.full(
                UpdateDeployment.builder()
                    .litellmParams(
                        UpdateDeployment.LitellmParams.builder()
                            .apiBase("api_base")
                            .apiKey("api_key")
                            .apiVersion("api_version")
                            .autoRouterConfig("auto_router_config")
                            .autoRouterConfigPath("auto_router_config_path")
                            .autoRouterDefaultModel("auto_router_default_model")
                            .autoRouterEmbeddingModel("auto_router_embedding_model")
                            .awsAccessKeyId("aws_access_key_id")
                            .awsBedrockRuntimeEndpoint("aws_bedrock_runtime_endpoint")
                            .awsRegionName("aws_region_name")
                            .awsSecretAccessKey("aws_secret_access_key")
                            .budgetDuration("budget_duration")
                            .cacheCreationInputAudioTokenCost(0.0)
                            .cacheCreationInputTokenCost(0.0)
                            .cacheCreationInputTokenCostAbove1hr(0.0)
                            .cacheCreationInputTokenCostAbove200kTokens(0.0)
                            .cacheReadInputAudioTokenCost(0.0)
                            .cacheReadInputTokenCost(0.0)
                            .cacheReadInputTokenCostAbove200kTokens(0.0)
                            .cacheReadInputTokenCostFlex(0.0)
                            .cacheReadInputTokenCostPriority(0.0)
                            .citationCostPerToken(0.0)
                            .addConfigurableClientsideAuthParam("string")
                            .customLlmProvider("custom_llm_provider")
                            .gcsBucketName("gcs_bucket_name")
                            .inputCostPerAudioPerSecond(0.0)
                            .inputCostPerAudioPerSecondAbove128kTokens(0.0)
                            .inputCostPerAudioToken(0.0)
                            .inputCostPerCharacter(0.0)
                            .inputCostPerCharacterAbove128kTokens(0.0)
                            .inputCostPerImage(0.0)
                            .inputCostPerImageAbove128kTokens(0.0)
                            .inputCostPerPixel(0.0)
                            .inputCostPerQuery(0.0)
                            .inputCostPerSecond(0.0)
                            .inputCostPerToken(0.0)
                            .inputCostPerTokenAbove128kTokens(0.0)
                            .inputCostPerTokenAbove200kTokens(0.0)
                            .inputCostPerTokenBatches(0.0)
                            .inputCostPerTokenCacheHit(0.0)
                            .inputCostPerTokenFlex(0.0)
                            .inputCostPerTokenPriority(0.0)
                            .inputCostPerVideoPerSecond(0.0)
                            .inputCostPerVideoPerSecondAbove128kTokens(0.0)
                            .inputCostPerVideoPerSecondAbove15sInterval(0.0)
                            .inputCostPerVideoPerSecondAbove8sInterval(0.0)
                            .litellmCredentialName("litellm_credential_name")
                            .litellmTraceId("litellm_trace_id")
                            .maxBudget(0.0)
                            .maxFileSizeMb(0.0)
                            .maxRetries(0L)
                            .mergeReasoningContentInChoices(true)
                            .milvusTextField("milvus_text_field")
                            .mockResponse("string")
                            .model("model")
                            .modelInfo(
                                UpdateDeployment.LitellmParams.ModelInfo.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .organization("organization")
                            .outputCostPerAudioPerSecond(0.0)
                            .outputCostPerAudioToken(0.0)
                            .outputCostPerCharacter(0.0)
                            .outputCostPerCharacterAbove128kTokens(0.0)
                            .outputCostPerImage(0.0)
                            .outputCostPerImageToken(0.0)
                            .outputCostPerPixel(0.0)
                            .outputCostPerReasoningToken(0.0)
                            .outputCostPerSecond(0.0)
                            .outputCostPerToken(0.0)
                            .outputCostPerTokenAbove128kTokens(0.0)
                            .outputCostPerTokenAbove200kTokens(0.0)
                            .outputCostPerTokenBatches(0.0)
                            .outputCostPerTokenFlex(0.0)
                            .outputCostPerTokenPriority(0.0)
                            .outputCostPerVideoPerSecond(0.0)
                            .regionName("region_name")
                            .rpm(0L)
                            .s3BucketName("s3_bucket_name")
                            .s3EncryptionKeyId("s3_encryption_key_id")
                            .searchContextCostPerQuery(
                                UpdateDeployment.LitellmParams.SearchContextCostPerQuery.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .streamTimeout(0.0)
                            .addTieredPricing(
                                UpdateDeployment.LitellmParams.TieredPricing.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .timeout(0.0)
                            .tpm(0L)
                            .useInPassThrough(true)
                            .useLitellmProxy(true)
                            .vectorStoreId("vector_store_id")
                            .vertexCredentials("string")
                            .vertexLocation("vertex_location")
                            .vertexProject("vertex_project")
                            .watsonxRegionName("watsonx_region_name")
                            .build()
                    )
                    .modelInfo(
                        ModelInfo.builder()
                            .id("id")
                            .baseModel("base_model")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .createdBy("created_by")
                            .dbModel(true)
                            .teamId("team_id")
                            .teamPublicModelName("team_public_model_name")
                            .tier(ModelInfo.Tier.FREE)
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .updatedBy("updated_by")
                            .build()
                    )
                    .modelName("model_name")
                    .build()
            )

        response.validate()
    }

    @Disabled("Prism tests are disabled")
    @Test
    fun partial() {
        val client =
            HanzoOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .apiKey("My API Key")
                .build()
        val updateService = client.model().update()

        val response =
            updateService.partial(
                UpdatePartialParams.builder()
                    .modelId("model_id")
                    .updateDeployment(
                        UpdateDeployment.builder()
                            .litellmParams(
                                UpdateDeployment.LitellmParams.builder()
                                    .apiBase("api_base")
                                    .apiKey("api_key")
                                    .apiVersion("api_version")
                                    .autoRouterConfig("auto_router_config")
                                    .autoRouterConfigPath("auto_router_config_path")
                                    .autoRouterDefaultModel("auto_router_default_model")
                                    .autoRouterEmbeddingModel("auto_router_embedding_model")
                                    .awsAccessKeyId("aws_access_key_id")
                                    .awsBedrockRuntimeEndpoint("aws_bedrock_runtime_endpoint")
                                    .awsRegionName("aws_region_name")
                                    .awsSecretAccessKey("aws_secret_access_key")
                                    .budgetDuration("budget_duration")
                                    .cacheCreationInputAudioTokenCost(0.0)
                                    .cacheCreationInputTokenCost(0.0)
                                    .cacheCreationInputTokenCostAbove1hr(0.0)
                                    .cacheCreationInputTokenCostAbove200kTokens(0.0)
                                    .cacheReadInputAudioTokenCost(0.0)
                                    .cacheReadInputTokenCost(0.0)
                                    .cacheReadInputTokenCostAbove200kTokens(0.0)
                                    .cacheReadInputTokenCostFlex(0.0)
                                    .cacheReadInputTokenCostPriority(0.0)
                                    .citationCostPerToken(0.0)
                                    .addConfigurableClientsideAuthParam("string")
                                    .customLlmProvider("custom_llm_provider")
                                    .gcsBucketName("gcs_bucket_name")
                                    .inputCostPerAudioPerSecond(0.0)
                                    .inputCostPerAudioPerSecondAbove128kTokens(0.0)
                                    .inputCostPerAudioToken(0.0)
                                    .inputCostPerCharacter(0.0)
                                    .inputCostPerCharacterAbove128kTokens(0.0)
                                    .inputCostPerImage(0.0)
                                    .inputCostPerImageAbove128kTokens(0.0)
                                    .inputCostPerPixel(0.0)
                                    .inputCostPerQuery(0.0)
                                    .inputCostPerSecond(0.0)
                                    .inputCostPerToken(0.0)
                                    .inputCostPerTokenAbove128kTokens(0.0)
                                    .inputCostPerTokenAbove200kTokens(0.0)
                                    .inputCostPerTokenBatches(0.0)
                                    .inputCostPerTokenCacheHit(0.0)
                                    .inputCostPerTokenFlex(0.0)
                                    .inputCostPerTokenPriority(0.0)
                                    .inputCostPerVideoPerSecond(0.0)
                                    .inputCostPerVideoPerSecondAbove128kTokens(0.0)
                                    .inputCostPerVideoPerSecondAbove15sInterval(0.0)
                                    .inputCostPerVideoPerSecondAbove8sInterval(0.0)
                                    .litellmCredentialName("litellm_credential_name")
                                    .litellmTraceId("litellm_trace_id")
                                    .maxBudget(0.0)
                                    .maxFileSizeMb(0.0)
                                    .maxRetries(0L)
                                    .mergeReasoningContentInChoices(true)
                                    .milvusTextField("milvus_text_field")
                                    .mockResponse("string")
                                    .model("model")
                                    .modelInfo(
                                        UpdateDeployment.LitellmParams.ModelInfo.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .organization("organization")
                                    .outputCostPerAudioPerSecond(0.0)
                                    .outputCostPerAudioToken(0.0)
                                    .outputCostPerCharacter(0.0)
                                    .outputCostPerCharacterAbove128kTokens(0.0)
                                    .outputCostPerImage(0.0)
                                    .outputCostPerImageToken(0.0)
                                    .outputCostPerPixel(0.0)
                                    .outputCostPerReasoningToken(0.0)
                                    .outputCostPerSecond(0.0)
                                    .outputCostPerToken(0.0)
                                    .outputCostPerTokenAbove128kTokens(0.0)
                                    .outputCostPerTokenAbove200kTokens(0.0)
                                    .outputCostPerTokenBatches(0.0)
                                    .outputCostPerTokenFlex(0.0)
                                    .outputCostPerTokenPriority(0.0)
                                    .outputCostPerVideoPerSecond(0.0)
                                    .regionName("region_name")
                                    .rpm(0L)
                                    .s3BucketName("s3_bucket_name")
                                    .s3EncryptionKeyId("s3_encryption_key_id")
                                    .searchContextCostPerQuery(
                                        UpdateDeployment.LitellmParams.SearchContextCostPerQuery
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .streamTimeout(0.0)
                                    .addTieredPricing(
                                        UpdateDeployment.LitellmParams.TieredPricing.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .timeout(0.0)
                                    .tpm(0L)
                                    .useInPassThrough(true)
                                    .useLitellmProxy(true)
                                    .vectorStoreId("vector_store_id")
                                    .vertexCredentials("string")
                                    .vertexLocation("vertex_location")
                                    .vertexProject("vertex_project")
                                    .watsonxRegionName("watsonx_region_name")
                                    .build()
                            )
                            .modelInfo(
                                ModelInfo.builder()
                                    .id("id")
                                    .baseModel("base_model")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .createdBy("created_by")
                                    .dbModel(true)
                                    .teamId("team_id")
                                    .teamPublicModelName("team_public_model_name")
                                    .tier(ModelInfo.Tier.FREE)
                                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .updatedBy("updated_by")
                                    .build()
                            )
                            .modelName("model_name")
                            .build()
                    )
                    .build()
            )

        response.validate()
    }
}
