// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.organization

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import ai.hanzo.api.models.team.Member
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class OrganizationTableWithMembersTest {

    @Test
    fun create() {
        val organizationTableWithMembers =
            OrganizationTableWithMembers.builder()
                .budgetId("budget_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .addModel("string")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .litellmBudgetTable(
                    BudgetTable.builder()
                        .budgetDuration("budget_duration")
                        .budgetId("budget_id")
                        .maxBudget(0.0)
                        .maxParallelRequests(0L)
                        .modelMaxBudget(
                            BudgetTable.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .rpmLimit(0L)
                        .softBudget(0.0)
                        .tpmLimit(0L)
                        .build()
                )
                .addMember(
                    OrganizationMembershipTable.builder()
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .organizationId("organization_id")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userId("user_id")
                        .budgetId("budget_id")
                        .litellmBudgetTable(
                            BudgetTable.builder()
                                .budgetDuration("budget_duration")
                                .budgetId("budget_id")
                                .maxBudget(0.0)
                                .maxParallelRequests(0L)
                                .modelMaxBudget(
                                    BudgetTable.ModelMaxBudget.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .rpmLimit(0L)
                                .softBudget(0.0)
                                .tpmLimit(0L)
                                .build()
                        )
                        .spend(0.0)
                        .user(JsonValue.from(mapOf<String, Any>()))
                        .userRole("user_role")
                        .build()
                )
                .metadata(
                    OrganizationTableWithMembers.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .objectPermission(
                    OrganizationTableWithMembers.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            OrganizationTableWithMembers.ObjectPermission.McpToolPermissions
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .organizationAlias("organization_alias")
                .organizationId("organization_id")
                .spend(0.0)
                .addTeam(
                    OrganizationTableWithMembers.Team.builder()
                        .teamId("team_id")
                        .addAdmin(JsonValue.from(mapOf<String, Any>()))
                        .blocked(true)
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .litellmModelTable(JsonValue.from(mapOf<String, Any>()))
                        .maxBudget(0.0)
                        .maxParallelRequests(0L)
                        .addMember(JsonValue.from(mapOf<String, Any>()))
                        .addMembersWithRole(
                            Member.builder()
                                .role(Member.Role.ADMIN)
                                .userEmail("user_email")
                                .userId("user_id")
                                .build()
                        )
                        .metadata(
                            OrganizationTableWithMembers.Team.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelId(0L)
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            OrganizationTableWithMembers.Team.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    OrganizationTableWithMembers.Team.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .objectPermissionId("object_permission_id")
                        .organizationId("organization_id")
                        .routerSettings(
                            OrganizationTableWithMembers.Team.RouterSettings.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .teamAlias("team_alias")
                        .addTeamMemberPermission("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addUser(
                    OrganizationTableWithMembers.User.builder()
                        .userId("user_id")
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .maxBudget(0.0)
                        .metadata(
                            OrganizationTableWithMembers.User.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelMaxBudget(
                            OrganizationTableWithMembers.User.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelSpend(
                            OrganizationTableWithMembers.User.ModelSpend.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            OrganizationTableWithMembers.User.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    OrganizationTableWithMembers.User.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .addOrganizationMembership(
                            OrganizationMembershipTable.builder()
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .organizationId("organization_id")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .userId("user_id")
                                .budgetId("budget_id")
                                .litellmBudgetTable(
                                    BudgetTable.builder()
                                        .budgetDuration("budget_duration")
                                        .budgetId("budget_id")
                                        .maxBudget(0.0)
                                        .maxParallelRequests(0L)
                                        .modelMaxBudget(
                                            BudgetTable.ModelMaxBudget.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .rpmLimit(0L)
                                        .softBudget(0.0)
                                        .tpmLimit(0L)
                                        .build()
                                )
                                .spend(0.0)
                                .user(JsonValue.from(mapOf<String, Any>()))
                                .userRole("user_role")
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .ssoUserId("sso_user_id")
                        .addTeam("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userAlias("user_alias")
                        .userEmail("user_email")
                        .userRole("user_role")
                        .build()
                )
                .build()

        assertThat(organizationTableWithMembers.budgetId()).isEqualTo("budget_id")
        assertThat(organizationTableWithMembers.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(organizationTableWithMembers.createdBy()).isEqualTo("created_by")
        assertThat(organizationTableWithMembers.models()).containsExactly("string")
        assertThat(organizationTableWithMembers.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(organizationTableWithMembers.updatedBy()).isEqualTo("updated_by")
        assertThat(organizationTableWithMembers.litellmBudgetTable())
            .isEqualTo(
                BudgetTable.builder()
                    .budgetDuration("budget_duration")
                    .budgetId("budget_id")
                    .maxBudget(0.0)
                    .maxParallelRequests(0L)
                    .modelMaxBudget(
                        BudgetTable.ModelMaxBudget.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .rpmLimit(0L)
                    .softBudget(0.0)
                    .tpmLimit(0L)
                    .build()
            )
        assertThat(organizationTableWithMembers.members())
            .containsExactly(
                OrganizationMembershipTable.builder()
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .organizationId("organization_id")
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .userId("user_id")
                    .budgetId("budget_id")
                    .litellmBudgetTable(
                        BudgetTable.builder()
                            .budgetDuration("budget_duration")
                            .budgetId("budget_id")
                            .maxBudget(0.0)
                            .maxParallelRequests(0L)
                            .modelMaxBudget(
                                BudgetTable.ModelMaxBudget.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .rpmLimit(0L)
                            .softBudget(0.0)
                            .tpmLimit(0L)
                            .build()
                    )
                    .spend(0.0)
                    .user(JsonValue.from(mapOf<String, Any>()))
                    .userRole("user_role")
                    .build()
            )
        assertThat(organizationTableWithMembers.metadata())
            .isEqualTo(
                OrganizationTableWithMembers.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(organizationTableWithMembers.objectPermission())
            .isEqualTo(
                OrganizationTableWithMembers.ObjectPermission.builder()
                    .objectPermissionId("object_permission_id")
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        OrganizationTableWithMembers.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(organizationTableWithMembers.objectPermissionId())
            .isEqualTo("object_permission_id")
        assertThat(organizationTableWithMembers.organizationAlias()).isEqualTo("organization_alias")
        assertThat(organizationTableWithMembers.organizationId()).isEqualTo("organization_id")
        assertThat(organizationTableWithMembers.spend()).isEqualTo(0.0)
        assertThat(organizationTableWithMembers.teams())
            .containsExactly(
                OrganizationTableWithMembers.Team.builder()
                    .teamId("team_id")
                    .addAdmin(JsonValue.from(mapOf<String, Any>()))
                    .blocked(true)
                    .budgetDuration("budget_duration")
                    .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .litellmModelTable(JsonValue.from(mapOf<String, Any>()))
                    .maxBudget(0.0)
                    .maxParallelRequests(0L)
                    .addMember(JsonValue.from(mapOf<String, Any>()))
                    .addMembersWithRole(
                        Member.builder()
                            .role(Member.Role.ADMIN)
                            .userEmail("user_email")
                            .userId("user_id")
                            .build()
                    )
                    .metadata(
                        OrganizationTableWithMembers.Team.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .modelId(0L)
                    .addModel(JsonValue.from(mapOf<String, Any>()))
                    .objectPermission(
                        OrganizationTableWithMembers.Team.ObjectPermission.builder()
                            .objectPermissionId("object_permission_id")
                            .addAgentAccessGroup("string")
                            .addAgent("string")
                            .addMcpAccessGroup("string")
                            .addMcpServer("string")
                            .mcpToolPermissions(
                                OrganizationTableWithMembers.Team.ObjectPermission
                                    .McpToolPermissions
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                    .build()
                            )
                            .addVectorStore("string")
                            .build()
                    )
                    .objectPermissionId("object_permission_id")
                    .organizationId("organization_id")
                    .routerSettings(
                        OrganizationTableWithMembers.Team.RouterSettings.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .rpmLimit(0L)
                    .spend(0.0)
                    .teamAlias("team_alias")
                    .addTeamMemberPermission("string")
                    .tpmLimit(0L)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(organizationTableWithMembers.users())
            .containsExactly(
                OrganizationTableWithMembers.User.builder()
                    .userId("user_id")
                    .budgetDuration("budget_duration")
                    .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .maxBudget(0.0)
                    .metadata(
                        OrganizationTableWithMembers.User.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .modelMaxBudget(
                        OrganizationTableWithMembers.User.ModelMaxBudget.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .modelSpend(
                        OrganizationTableWithMembers.User.ModelSpend.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .addModel(JsonValue.from(mapOf<String, Any>()))
                    .objectPermission(
                        OrganizationTableWithMembers.User.ObjectPermission.builder()
                            .objectPermissionId("object_permission_id")
                            .addAgentAccessGroup("string")
                            .addAgent("string")
                            .addMcpAccessGroup("string")
                            .addMcpServer("string")
                            .mcpToolPermissions(
                                OrganizationTableWithMembers.User.ObjectPermission
                                    .McpToolPermissions
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                    .build()
                            )
                            .addVectorStore("string")
                            .build()
                    )
                    .addOrganizationMembership(
                        OrganizationMembershipTable.builder()
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .organizationId("organization_id")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .userId("user_id")
                            .budgetId("budget_id")
                            .litellmBudgetTable(
                                BudgetTable.builder()
                                    .budgetDuration("budget_duration")
                                    .budgetId("budget_id")
                                    .maxBudget(0.0)
                                    .maxParallelRequests(0L)
                                    .modelMaxBudget(
                                        BudgetTable.ModelMaxBudget.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .rpmLimit(0L)
                                    .softBudget(0.0)
                                    .tpmLimit(0L)
                                    .build()
                            )
                            .spend(0.0)
                            .user(JsonValue.from(mapOf<String, Any>()))
                            .userRole("user_role")
                            .build()
                    )
                    .rpmLimit(0L)
                    .spend(0.0)
                    .ssoUserId("sso_user_id")
                    .addTeam("string")
                    .tpmLimit(0L)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .userAlias("user_alias")
                    .userEmail("user_email")
                    .userRole("user_role")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val organizationTableWithMembers =
            OrganizationTableWithMembers.builder()
                .budgetId("budget_id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .addModel("string")
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .litellmBudgetTable(
                    BudgetTable.builder()
                        .budgetDuration("budget_duration")
                        .budgetId("budget_id")
                        .maxBudget(0.0)
                        .maxParallelRequests(0L)
                        .modelMaxBudget(
                            BudgetTable.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .rpmLimit(0L)
                        .softBudget(0.0)
                        .tpmLimit(0L)
                        .build()
                )
                .addMember(
                    OrganizationMembershipTable.builder()
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .organizationId("organization_id")
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userId("user_id")
                        .budgetId("budget_id")
                        .litellmBudgetTable(
                            BudgetTable.builder()
                                .budgetDuration("budget_duration")
                                .budgetId("budget_id")
                                .maxBudget(0.0)
                                .maxParallelRequests(0L)
                                .modelMaxBudget(
                                    BudgetTable.ModelMaxBudget.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .rpmLimit(0L)
                                .softBudget(0.0)
                                .tpmLimit(0L)
                                .build()
                        )
                        .spend(0.0)
                        .user(JsonValue.from(mapOf<String, Any>()))
                        .userRole("user_role")
                        .build()
                )
                .metadata(
                    OrganizationTableWithMembers.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .objectPermission(
                    OrganizationTableWithMembers.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            OrganizationTableWithMembers.ObjectPermission.McpToolPermissions
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .organizationAlias("organization_alias")
                .organizationId("organization_id")
                .spend(0.0)
                .addTeam(
                    OrganizationTableWithMembers.Team.builder()
                        .teamId("team_id")
                        .addAdmin(JsonValue.from(mapOf<String, Any>()))
                        .blocked(true)
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .litellmModelTable(JsonValue.from(mapOf<String, Any>()))
                        .maxBudget(0.0)
                        .maxParallelRequests(0L)
                        .addMember(JsonValue.from(mapOf<String, Any>()))
                        .addMembersWithRole(
                            Member.builder()
                                .role(Member.Role.ADMIN)
                                .userEmail("user_email")
                                .userId("user_id")
                                .build()
                        )
                        .metadata(
                            OrganizationTableWithMembers.Team.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelId(0L)
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            OrganizationTableWithMembers.Team.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    OrganizationTableWithMembers.Team.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .objectPermissionId("object_permission_id")
                        .organizationId("organization_id")
                        .routerSettings(
                            OrganizationTableWithMembers.Team.RouterSettings.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .teamAlias("team_alias")
                        .addTeamMemberPermission("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .addUser(
                    OrganizationTableWithMembers.User.builder()
                        .userId("user_id")
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .maxBudget(0.0)
                        .metadata(
                            OrganizationTableWithMembers.User.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelMaxBudget(
                            OrganizationTableWithMembers.User.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelSpend(
                            OrganizationTableWithMembers.User.ModelSpend.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            OrganizationTableWithMembers.User.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    OrganizationTableWithMembers.User.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .addOrganizationMembership(
                            OrganizationMembershipTable.builder()
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .organizationId("organization_id")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .userId("user_id")
                                .budgetId("budget_id")
                                .litellmBudgetTable(
                                    BudgetTable.builder()
                                        .budgetDuration("budget_duration")
                                        .budgetId("budget_id")
                                        .maxBudget(0.0)
                                        .maxParallelRequests(0L)
                                        .modelMaxBudget(
                                            BudgetTable.ModelMaxBudget.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .rpmLimit(0L)
                                        .softBudget(0.0)
                                        .tpmLimit(0L)
                                        .build()
                                )
                                .spend(0.0)
                                .user(JsonValue.from(mapOf<String, Any>()))
                                .userRole("user_role")
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .ssoUserId("sso_user_id")
                        .addTeam("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userAlias("user_alias")
                        .userEmail("user_email")
                        .userRole("user_role")
                        .build()
                )
                .build()

        val roundtrippedOrganizationTableWithMembers =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(organizationTableWithMembers),
                jacksonTypeRef<OrganizationTableWithMembers>(),
            )

        assertThat(roundtrippedOrganizationTableWithMembers).isEqualTo(organizationTableWithMembers)
    }
}
