// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.key

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class GenerateKeyResponseTest {

    @Test
    fun create() {
        val generateKeyResponse =
            GenerateKeyResponse.builder()
                .key("key")
                .token("token")
                .aliases(
                    GenerateKeyResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    GenerateKeyResponse.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            GenerateKeyResponse.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    GenerateKeyResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .duration("duration")
                .addEnforcedParam("string")
                .expires(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addGuardrail("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .litellmBudgetTable(JsonValue.from(mapOf<String, Any>()))
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    GenerateKeyResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    GenerateKeyResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    GenerateKeyResponse.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    GenerateKeyResponse.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    GenerateKeyResponse.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            GenerateKeyResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    GenerateKeyResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .routerSettings(
                    GenerateKeyResponse.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            GenerateKeyResponse.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            GenerateKeyResponse.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            GenerateKeyResponse.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            GenerateKeyResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            GenerateKeyResponse.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(GenerateKeyResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .tokenId("token_id")
                .tpmLimit(0L)
                .tpmLimitType(GenerateKeyResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userId("user_id")
                .build()

        assertThat(generateKeyResponse.key()).isEqualTo("key")
        assertThat(generateKeyResponse.token()).isEqualTo("token")
        assertThat(generateKeyResponse.aliases())
            .isEqualTo(
                GenerateKeyResponse.Aliases.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.allowedCacheControls())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(generateKeyResponse.allowedPassthroughRoutes())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(generateKeyResponse.allowedRoutes())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(generateKeyResponse.allowedVectorStoreIndexes())
            .containsExactly(
                GenerateKeyResponse.AllowedVectorStoreIndex.builder()
                    .indexName("index_name")
                    .addIndexPermission(
                        GenerateKeyResponse.AllowedVectorStoreIndex.IndexPermission.READ
                    )
                    .build()
            )
        assertThat(generateKeyResponse.blocked()).isEqualTo(true)
        assertThat(generateKeyResponse.budgetDuration()).isEqualTo("budget_duration")
        assertThat(generateKeyResponse.budgetId()).isEqualTo("budget_id")
        assertThat(generateKeyResponse.config())
            .isEqualTo(
                GenerateKeyResponse.Config.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(generateKeyResponse.createdBy()).isEqualTo("created_by")
        assertThat(generateKeyResponse.duration()).isEqualTo("duration")
        assertThat(generateKeyResponse.enforcedParams()).containsExactly("string")
        assertThat(generateKeyResponse.expires())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(generateKeyResponse.guardrails()).containsExactly("string")
        assertThat(generateKeyResponse.keyAlias()).isEqualTo("key_alias")
        assertThat(generateKeyResponse.keyName()).isEqualTo("key_name")
        assertThat(generateKeyResponse._litellmBudgetTable())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(generateKeyResponse.maxBudget()).isEqualTo(0.0)
        assertThat(generateKeyResponse.maxParallelRequests()).isEqualTo(0L)
        assertThat(generateKeyResponse.metadata())
            .isEqualTo(
                GenerateKeyResponse.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.modelMaxBudget())
            .isEqualTo(
                GenerateKeyResponse.ModelMaxBudget.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.modelRpmLimit())
            .isEqualTo(
                GenerateKeyResponse.ModelRpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.modelTpmLimit())
            .isEqualTo(
                GenerateKeyResponse.ModelTpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.models())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(generateKeyResponse.objectPermission())
            .isEqualTo(
                GenerateKeyResponse.ObjectPermission.builder()
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        GenerateKeyResponse.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(generateKeyResponse.organizationId()).isEqualTo("organization_id")
        assertThat(generateKeyResponse.permissions())
            .isEqualTo(
                GenerateKeyResponse.Permissions.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(generateKeyResponse.prompts()).containsExactly("string")
        assertThat(generateKeyResponse.routerSettings())
            .isEqualTo(
                GenerateKeyResponse.RouterSettings.builder()
                    .allowedFails(0L)
                    .addContextWindowFallback(
                        GenerateKeyResponse.RouterSettings.ContextWindowFallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .cooldownTime(0.0)
                    .addFallback(
                        GenerateKeyResponse.RouterSettings.Fallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .maxRetries(0L)
                    .modelGroupAlias(
                        GenerateKeyResponse.RouterSettings.ModelGroupAlias.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .modelGroupRetryPolicy(
                        GenerateKeyResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .numRetries(0L)
                    .retryAfter(0.0)
                    .routingStrategy("routing_strategy")
                    .routingStrategyArgs(
                        GenerateKeyResponse.RouterSettings.RoutingStrategyArgs.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .timeout(0.0)
                    .build()
            )
        assertThat(generateKeyResponse.rpmLimit()).isEqualTo(0L)
        assertThat(generateKeyResponse.rpmLimitType())
            .isEqualTo(GenerateKeyResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(generateKeyResponse.spend()).isEqualTo(0.0)
        assertThat(generateKeyResponse.tags()).containsExactly("string")
        assertThat(generateKeyResponse.teamId()).isEqualTo("team_id")
        assertThat(generateKeyResponse.tokenId()).isEqualTo("token_id")
        assertThat(generateKeyResponse.tpmLimit()).isEqualTo(0L)
        assertThat(generateKeyResponse.tpmLimitType())
            .isEqualTo(GenerateKeyResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(generateKeyResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(generateKeyResponse.updatedBy()).isEqualTo("updated_by")
        assertThat(generateKeyResponse.userId()).isEqualTo("user_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val generateKeyResponse =
            GenerateKeyResponse.builder()
                .key("key")
                .token("token")
                .aliases(
                    GenerateKeyResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    GenerateKeyResponse.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            GenerateKeyResponse.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    GenerateKeyResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .duration("duration")
                .addEnforcedParam("string")
                .expires(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addGuardrail("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .litellmBudgetTable(JsonValue.from(mapOf<String, Any>()))
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    GenerateKeyResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    GenerateKeyResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    GenerateKeyResponse.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    GenerateKeyResponse.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    GenerateKeyResponse.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            GenerateKeyResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    GenerateKeyResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .routerSettings(
                    GenerateKeyResponse.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            GenerateKeyResponse.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            GenerateKeyResponse.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            GenerateKeyResponse.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            GenerateKeyResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            GenerateKeyResponse.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(GenerateKeyResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .tokenId("token_id")
                .tpmLimit(0L)
                .tpmLimitType(GenerateKeyResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userId("user_id")
                .build()

        val roundtrippedGenerateKeyResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(generateKeyResponse),
                jacksonTypeRef<GenerateKeyResponse>(),
            )

        assertThat(roundtrippedGenerateKeyResponse).isEqualTo(generateKeyResponse)
    }
}
