// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.key

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class KeyBlockResponseTest {

    @Test
    fun create() {
        val keyBlockResponse =
            KeyBlockResponse.builder()
                .token("token")
                .aliases(
                    KeyBlockResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .autoRotate(true)
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .config(
                    KeyBlockResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .expires("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .keyRotationAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .lastRotationAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .litellmBudgetTable(
                    KeyBlockResponse.LitellmBudgetTable.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    KeyBlockResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    KeyBlockResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelSpend(
                    KeyBlockResponse.ModelSpend.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    KeyBlockResponse.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            KeyBlockResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .orgId("org_id")
                .permissions(
                    KeyBlockResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rotationCount(0L)
                .rotationInterval("rotation_interval")
                .routerSettings(
                    KeyBlockResponse.RouterSettings.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rpmLimit(0L)
                .softBudgetCooldown(true)
                .spend(0.0)
                .teamId("team_id")
                .tpmLimit(0L)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userId("user_id")
                .build()

        assertThat(keyBlockResponse.token()).isEqualTo("token")
        assertThat(keyBlockResponse.aliases())
            .isEqualTo(
                KeyBlockResponse.Aliases.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.allowedCacheControls())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(keyBlockResponse.allowedRoutes())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(keyBlockResponse.autoRotate()).isEqualTo(true)
        assertThat(keyBlockResponse.blocked()).isEqualTo(true)
        assertThat(keyBlockResponse.budgetDuration()).isEqualTo("budget_duration")
        assertThat(keyBlockResponse.budgetResetAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(keyBlockResponse.config())
            .isEqualTo(
                KeyBlockResponse.Config.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(keyBlockResponse.createdBy()).isEqualTo("created_by")
        assertThat(keyBlockResponse.expires())
            .isEqualTo(KeyBlockResponse.Expires.ofString("string"))
        assertThat(keyBlockResponse.keyAlias()).isEqualTo("key_alias")
        assertThat(keyBlockResponse.keyName()).isEqualTo("key_name")
        assertThat(keyBlockResponse.keyRotationAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(keyBlockResponse.lastRotationAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(keyBlockResponse.litellmBudgetTable())
            .isEqualTo(
                KeyBlockResponse.LitellmBudgetTable.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.maxBudget()).isEqualTo(0.0)
        assertThat(keyBlockResponse.maxParallelRequests()).isEqualTo(0L)
        assertThat(keyBlockResponse.metadata())
            .isEqualTo(
                KeyBlockResponse.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.modelMaxBudget())
            .isEqualTo(
                KeyBlockResponse.ModelMaxBudget.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.modelSpend())
            .isEqualTo(
                KeyBlockResponse.ModelSpend.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.models()).containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(keyBlockResponse.objectPermission())
            .isEqualTo(
                KeyBlockResponse.ObjectPermission.builder()
                    .objectPermissionId("object_permission_id")
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        KeyBlockResponse.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(keyBlockResponse.objectPermissionId()).isEqualTo("object_permission_id")
        assertThat(keyBlockResponse.orgId()).isEqualTo("org_id")
        assertThat(keyBlockResponse.permissions())
            .isEqualTo(
                KeyBlockResponse.Permissions.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.rotationCount()).isEqualTo(0L)
        assertThat(keyBlockResponse.rotationInterval()).isEqualTo("rotation_interval")
        assertThat(keyBlockResponse.routerSettings())
            .isEqualTo(
                KeyBlockResponse.RouterSettings.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(keyBlockResponse.rpmLimit()).isEqualTo(0L)
        assertThat(keyBlockResponse.softBudgetCooldown()).isEqualTo(true)
        assertThat(keyBlockResponse.spend()).isEqualTo(0.0)
        assertThat(keyBlockResponse.teamId()).isEqualTo("team_id")
        assertThat(keyBlockResponse.tpmLimit()).isEqualTo(0L)
        assertThat(keyBlockResponse.updatedAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(keyBlockResponse.updatedBy()).isEqualTo("updated_by")
        assertThat(keyBlockResponse.userId()).isEqualTo("user_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val keyBlockResponse =
            KeyBlockResponse.builder()
                .token("token")
                .aliases(
                    KeyBlockResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .autoRotate(true)
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .config(
                    KeyBlockResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .expires("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .keyRotationAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .lastRotationAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .litellmBudgetTable(
                    KeyBlockResponse.LitellmBudgetTable.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    KeyBlockResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    KeyBlockResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelSpend(
                    KeyBlockResponse.ModelSpend.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    KeyBlockResponse.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            KeyBlockResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .orgId("org_id")
                .permissions(
                    KeyBlockResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rotationCount(0L)
                .rotationInterval("rotation_interval")
                .routerSettings(
                    KeyBlockResponse.RouterSettings.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rpmLimit(0L)
                .softBudgetCooldown(true)
                .spend(0.0)
                .teamId("team_id")
                .tpmLimit(0L)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userId("user_id")
                .build()

        val roundtrippedKeyBlockResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(keyBlockResponse),
                jacksonTypeRef<KeyBlockResponse>(),
            )

        assertThat(roundtrippedKeyBlockResponse).isEqualTo(keyBlockResponse)
    }
}
