// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.key.regenerate

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class RegenerateKeyRequestTest {

    @Test
    fun create() {
        val regenerateKeyRequest =
            RegenerateKeyRequest.builder()
                .aliases(
                    RegenerateKeyRequest.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    RegenerateKeyRequest.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            RegenerateKeyRequest.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .autoRotate(true)
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    RegenerateKeyRequest.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .duration("duration")
                .addEnforcedParam("string")
                .addGuardrail("string")
                .key("key")
                .keyAlias("key_alias")
                .keyType(RegenerateKeyRequest.KeyType.LLM_API)
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    RegenerateKeyRequest.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    RegenerateKeyRequest.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    RegenerateKeyRequest.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    RegenerateKeyRequest.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .newKey("new_key")
                .newMasterKey("new_master_key")
                .objectPermission(
                    RegenerateKeyRequest.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            RegenerateKeyRequest.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    RegenerateKeyRequest.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .rotationInterval("rotation_interval")
                .routerSettings(
                    RegenerateKeyRequest.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            RegenerateKeyRequest.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            RegenerateKeyRequest.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            RegenerateKeyRequest.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            RegenerateKeyRequest.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            RegenerateKeyRequest.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(RegenerateKeyRequest.RpmLimitType.GUARANTEED_THROUGHPUT)
                .sendInviteEmail(true)
                .softBudget(0.0)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .tpmLimit(0L)
                .tpmLimitType(RegenerateKeyRequest.TpmLimitType.GUARANTEED_THROUGHPUT)
                .userId("user_id")
                .build()

        assertThat(regenerateKeyRequest.aliases())
            .isEqualTo(
                RegenerateKeyRequest.Aliases.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.allowedCacheControls())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(regenerateKeyRequest.allowedPassthroughRoutes())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(regenerateKeyRequest.allowedRoutes())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(regenerateKeyRequest.allowedVectorStoreIndexes())
            .containsExactly(
                RegenerateKeyRequest.AllowedVectorStoreIndex.builder()
                    .indexName("index_name")
                    .addIndexPermission(
                        RegenerateKeyRequest.AllowedVectorStoreIndex.IndexPermission.READ
                    )
                    .build()
            )
        assertThat(regenerateKeyRequest.autoRotate()).isEqualTo(true)
        assertThat(regenerateKeyRequest.blocked()).isEqualTo(true)
        assertThat(regenerateKeyRequest.budgetDuration()).isEqualTo("budget_duration")
        assertThat(regenerateKeyRequest.budgetId()).isEqualTo("budget_id")
        assertThat(regenerateKeyRequest.config())
            .isEqualTo(
                RegenerateKeyRequest.Config.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.duration()).isEqualTo("duration")
        assertThat(regenerateKeyRequest.enforcedParams()).containsExactly("string")
        assertThat(regenerateKeyRequest.guardrails()).containsExactly("string")
        assertThat(regenerateKeyRequest.key()).isEqualTo("key")
        assertThat(regenerateKeyRequest.keyAlias()).isEqualTo("key_alias")
        assertThat(regenerateKeyRequest.keyType()).isEqualTo(RegenerateKeyRequest.KeyType.LLM_API)
        assertThat(regenerateKeyRequest.maxBudget()).isEqualTo(0.0)
        assertThat(regenerateKeyRequest.maxParallelRequests()).isEqualTo(0L)
        assertThat(regenerateKeyRequest.metadata())
            .isEqualTo(
                RegenerateKeyRequest.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.modelMaxBudget())
            .isEqualTo(
                RegenerateKeyRequest.ModelMaxBudget.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.modelRpmLimit())
            .isEqualTo(
                RegenerateKeyRequest.ModelRpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.modelTpmLimit())
            .isEqualTo(
                RegenerateKeyRequest.ModelTpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.models())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(regenerateKeyRequest.newKey()).isEqualTo("new_key")
        assertThat(regenerateKeyRequest.newMasterKey()).isEqualTo("new_master_key")
        assertThat(regenerateKeyRequest.objectPermission())
            .isEqualTo(
                RegenerateKeyRequest.ObjectPermission.builder()
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        RegenerateKeyRequest.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(regenerateKeyRequest.organizationId()).isEqualTo("organization_id")
        assertThat(regenerateKeyRequest.permissions())
            .isEqualTo(
                RegenerateKeyRequest.Permissions.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(regenerateKeyRequest.prompts()).containsExactly("string")
        assertThat(regenerateKeyRequest.rotationInterval()).isEqualTo("rotation_interval")
        assertThat(regenerateKeyRequest.routerSettings())
            .isEqualTo(
                RegenerateKeyRequest.RouterSettings.builder()
                    .allowedFails(0L)
                    .addContextWindowFallback(
                        RegenerateKeyRequest.RouterSettings.ContextWindowFallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .cooldownTime(0.0)
                    .addFallback(
                        RegenerateKeyRequest.RouterSettings.Fallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .maxRetries(0L)
                    .modelGroupAlias(
                        RegenerateKeyRequest.RouterSettings.ModelGroupAlias.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .modelGroupRetryPolicy(
                        RegenerateKeyRequest.RouterSettings.ModelGroupRetryPolicy.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .numRetries(0L)
                    .retryAfter(0.0)
                    .routingStrategy("routing_strategy")
                    .routingStrategyArgs(
                        RegenerateKeyRequest.RouterSettings.RoutingStrategyArgs.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .timeout(0.0)
                    .build()
            )
        assertThat(regenerateKeyRequest.rpmLimit()).isEqualTo(0L)
        assertThat(regenerateKeyRequest.rpmLimitType())
            .isEqualTo(RegenerateKeyRequest.RpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(regenerateKeyRequest.sendInviteEmail()).isEqualTo(true)
        assertThat(regenerateKeyRequest.softBudget()).isEqualTo(0.0)
        assertThat(regenerateKeyRequest.spend()).isEqualTo(0.0)
        assertThat(regenerateKeyRequest.tags()).containsExactly("string")
        assertThat(regenerateKeyRequest.teamId()).isEqualTo("team_id")
        assertThat(regenerateKeyRequest.tpmLimit()).isEqualTo(0L)
        assertThat(regenerateKeyRequest.tpmLimitType())
            .isEqualTo(RegenerateKeyRequest.TpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(regenerateKeyRequest.userId()).isEqualTo("user_id")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val regenerateKeyRequest =
            RegenerateKeyRequest.builder()
                .aliases(
                    RegenerateKeyRequest.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    RegenerateKeyRequest.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            RegenerateKeyRequest.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .autoRotate(true)
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    RegenerateKeyRequest.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .duration("duration")
                .addEnforcedParam("string")
                .addGuardrail("string")
                .key("key")
                .keyAlias("key_alias")
                .keyType(RegenerateKeyRequest.KeyType.LLM_API)
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    RegenerateKeyRequest.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    RegenerateKeyRequest.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    RegenerateKeyRequest.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    RegenerateKeyRequest.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .newKey("new_key")
                .newMasterKey("new_master_key")
                .objectPermission(
                    RegenerateKeyRequest.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            RegenerateKeyRequest.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    RegenerateKeyRequest.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .rotationInterval("rotation_interval")
                .routerSettings(
                    RegenerateKeyRequest.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            RegenerateKeyRequest.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            RegenerateKeyRequest.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            RegenerateKeyRequest.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            RegenerateKeyRequest.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            RegenerateKeyRequest.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(RegenerateKeyRequest.RpmLimitType.GUARANTEED_THROUGHPUT)
                .sendInviteEmail(true)
                .softBudget(0.0)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .tpmLimit(0L)
                .tpmLimitType(RegenerateKeyRequest.TpmLimitType.GUARANTEED_THROUGHPUT)
                .userId("user_id")
                .build()

        val roundtrippedRegenerateKeyRequest =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(regenerateKeyRequest),
                jacksonTypeRef<RegenerateKeyRequest>(),
            )

        assertThat(roundtrippedRegenerateKeyRequest).isEqualTo(regenerateKeyRequest)
    }
}
